apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: opendistro
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: amazon/opendistro-for-elasticsearch:1.10.1
        env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9600
          name: analyzer
          protocol: TCP
        volumeMounts:
        - name: opendistro-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      - name: kibana
        image: amazon/opendistro-for-elasticsearch-kibana:1.10.1
        env:
        - name: ELASTICSEARCH_URL
          value: https://localhost:9200
        - name: ELASTICSEARCH_HOSTS
          value: https://localhost:9200
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
      volumes:
      - name: opendistro-persistent-storage
        persistentVolumeClaim:
          claimName: opendistro-pv-claim
