apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendistro-pv-claim
  labels:
    component: elasticsearch
  namespace: opendistro
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
